[31mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.NDR:13: WARNING: Unexpected indentation.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:2: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:7: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:16: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[31mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:19: WARNING: Unexpected indentation.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:20: WARNING: Enumerated list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:21: WARNING: Block quote ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:22: WARNING: Enumerated list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:23: WARNING: Block quote ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:24: WARNING: Enumerated list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:25: WARNING: Block quote ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.Split:47: WARNING: Explicit markup ends without a blank line; unexpected unindent.[39;49;00m
[31mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._ClassificationSplit:7: WARNING: Unexpected indentation.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._ClassificationSplit:8: WARNING: Block quote ends without a blank line; unexpected unindent.[39;49;00m
[31mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._ReidentificationSplit:8: WARNING: Unexpected indentation.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._ReidentificationSplit:14: WARNING: Block quote ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._ReidentificationSplit:30: WARNING: Explicit markup ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._InstanceSpecificSplit:21: WARNING: Definition list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.Rename:10: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.Rename:13: WARNING: Explicit markup ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.Rename:14: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.Rename:17: WARNING: Explicit markup ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.Rename:18: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.RemapLabels:11: WARNING: Definition list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.RemapLabels:15: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.RemapLabels:18: WARNING: Explicit markup ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.RemapLabels:19: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.RemapLabels:22: WARNING: Explicit markup ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.RemapLabels:23: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.ProjectLabels:14: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.ResizeTransform:6: WARNING: Bullet list ends without a blank line; unexpected unindent.[39;49;00m
[31mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.Rename:13: WARNING: Unknown target name: "frame".[39;49;00m
[31mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\entropy.py:docstring of datumaro.plugins.sampler.algorithm.entropy.SampleEntropy._get_sample_mixed:3: WARNING: Unexpected indentation.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\entropy.py:docstring of datumaro.plugins.sampler.algorithm.entropy.SampleEntropy._get_sample_mixed:6: WARNING: Block quote ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\random_sampler.py:docstring of datumaro.plugins.sampler.random_sampler.RandomSampler:13: WARNING: Explicit markup ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\random_sampler.py:docstring of datumaro.plugins.sampler.random_sampler.LabelRandomSampler:24: WARNING: Explicit markup ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\relevancy_sampler.py:docstring of datumaro.plugins.sampler.relevancy_sampler.RelevancySampler:27: WARNING: Definition list ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\mask_tools.py:docstring of datumaro.util.mask_tools.crop_covered_segments:22: WARNING: Block quote ends without a blank line; unexpected unindent.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\test_utils.py:docstring of datumaro.util.test_utils:1: WARNING: duplicate object description of datumaro.util.test_utils, other instance in api/util/util/datumaro.util.test_utils, use :noindex: for one of them[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\test_utils.py:docstring of datumaro.util.test_utils.Dimensions:1: WARNING: duplicate object description of datumaro.util.test_utils.Dimensions, other instance in api/util/util/datumaro.util.test_utils, use :noindex: for one of them[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\test_utils.py:docstring of datumaro.util.test_utils.Dimensions.dim_2d:1: WARNING: duplicate object description of datumaro.util.test_utils.Dimensions.dim_2d, other instance in api/util/util/datumaro.util.test_utils, use :noindex: for one of them[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\test_utils.py:docstring of datumaro.util.test_utils.Dimensions.dim_3d:1: WARNING: duplicate object description of datumaro.util.test_utils.Dimensions.dim_3d, other instance in api/util/util/datumaro.util.test_utils, use :noindex: for one of them[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\cli\util\__init__.py:docstring of datumaro.cli.util.MultilineFormatter:1: WARNING: py:class reference target not found: argparse.HelpFormatter[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\cli\util\__init__.py:docstring of datumaro.cli.util.join_cli_args:: WARNING: py:class reference target not found: argparse.Namespace[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\cli\util\project.py:docstring of datumaro.cli.util.project.split_local_revpath:: WARNING: py:class reference target not found: Revision[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.AnnotationType:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.LabelCategories.find:: WARNING: py:class reference target not found: Category[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.LabelCategories.__getitem__:: WARNING: py:class reference target not found: Category[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.LabelCategories.__iter__:: WARNING: py:class reference target not found: Category[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Mask.image:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Mask.as_class_mask:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Mask.as_instance_mask:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Mask.paint:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.RleMask.image:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask.__init__:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask.__init__:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask.__init__:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask.__init__:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask.class_mask:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask.instance_mask:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask.extract:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.CompiledMask.lazy_extract:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.PolyLine:1: WARNING: py:class reference target not found: datumaro.components.annotation._Shape[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Polygon:1: WARNING: py:class reference target not found: datumaro.components.annotation._Shape[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Bbox:1: WARNING: py:class reference target not found: datumaro.components.annotation._Shape[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Bbox.iou:: WARNING: py:class reference target not found: datumaro.components.annotation._Shape[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Bbox.iou:: WARNING: py:class reference target not found: Union[float, Literal[-1]][39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.PointsCategories:: WARNING: py:class reference target not found: Category[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Points:1: WARNING: py:class reference target not found: datumaro.components.annotation._Shape[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\annotation.py:docstring of datumaro.components.annotation.Points.Visibility:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\dataset.py:docstring of datumaro.components.dataset.ItemStatus:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\environment.py:docstring of datumaro.components.environment.Registry:1: WARNING: py:obj reference target not found: datumaro.components.environment.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\environment.py:docstring of datumaro.components.environment.Registry.register:: WARNING: py:class reference target not found: datumaro.components.environment.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\environment.py:docstring of datumaro.components.environment.Registry.register:: WARNING: py:class reference target not found: datumaro.components.environment.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\environment.py:docstring of datumaro.components.environment.Registry.unregister:: WARNING: py:class reference target not found: datumaro.components.environment.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\environment.py:docstring of datumaro.components.environment.Registry.__getitem__:: WARNING: py:class reference target not found: datumaro.components.environment.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\environment.py:docstring of datumaro.components.environment.Registry.__iter__:: WARNING: py:class reference target not found: datumaro.components.environment.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\extractor.py:docstring of datumaro.components.extractor.Extractor:1: WARNING: py:class reference target not found: datumaro.components.extractor._ExtractorBase[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\extractor.py:docstring of datumaro.components.extractor.Transform:1: WARNING: py:class reference target not found: datumaro.components.extractor._ExtractorBase[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\format_detection.py:docstring of datumaro.components.format_detection.FormatDetectionConfidence:1: WARNING: py:class reference target not found: enum.IntEnum[39;49;00m
[91m<unknown>:1: WARNING: py:obj reference target not found: typing.Optional[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\format_detection.py:docstring of datumaro.components.format_detection.RejectionReason:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\media.py:docstring of datumaro.components.media.Image:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\media.py:docstring of datumaro.components.media.Image:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\media.py:docstring of datumaro.components.media.Image.__init__:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\media.py:docstring of datumaro.components.media.Image.__init__:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\media.py:docstring of datumaro.components.media.Image.data:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: float array of shape N[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: 2 * d[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: d = dimensions of values[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: integer array of shape N[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: function[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: idx[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: stats[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: function[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: idx[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\operations.py:docstring of datumaro.components.operations._MeanStdCounter._compute_stats:: WARNING: py:class reference target not found: stats[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\project.py:docstring of datumaro.components.project.IgnoreMode:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\project.py:docstring of datumaro.components.project.ProjectSources:1: WARNING: py:class reference target not found: datumaro.components.project.CrudProxy[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\project.py:docstring of datumaro.components.project.BuildStageType:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\project.py:docstring of datumaro.components.project.ProjectBuildTargets:1: WARNING: py:class reference target not found: datumaro.components.project.CrudProxy[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\project.py:docstring of datumaro.components.project.DiffStatus:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\validator.py:docstring of datumaro.components.validator.Severity:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\validator.py:docstring of datumaro.components.validator.TaskType:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\validator.py:docstring of datumaro.components.validator.Validator.validate:: WARNING: py:class reference target not found: IDataset[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\validator.py:docstring of datumaro.components.validator.Validator.validate:: WARNING: py:class reference target not found: validation_results[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\validator.py:docstring of datumaro.components.validator.Validator.compute_statistics:: WARNING: py:class reference target not found: IDataset[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\components\validator.py:docstring of datumaro.components.validator.Validator.compute_statistics:: WARNING: py:class reference target not found: stats[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\site\source\api\datumaro.rst:17: WARNING: py:class reference target not found: datumaro.components.annotation.BinaryMaskImage[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\site\source\api\datumaro.rst:22: WARNING: py:class reference target not found: datumaro.components.annotation.CompiledMaskImage[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\site\source\api\datumaro.rst:24: WARNING: py:class reference target not found: datumaro.components.annotation.IndexMaskImage[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\site\source\api\datumaro.rst:34: WARNING: py:class reference target not found: datumaro.components.annotation.RleMask>[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\converter.py:docstring of datumaro.plugins.coco_format.converter.SegmentationMode:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\extractor.py:docstring of datumaro.plugins.coco_format.extractor.CocoImageInfoExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.coco_format.extractor._CocoExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\extractor.py:docstring of datumaro.plugins.coco_format.extractor.CocoCaptionsExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.coco_format.extractor._CocoExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\extractor.py:docstring of datumaro.plugins.coco_format.extractor.CocoInstancesExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.coco_format.extractor._CocoExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\extractor.py:docstring of datumaro.plugins.coco_format.extractor.CocoPersonKeypointsExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.coco_format.extractor._CocoExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\extractor.py:docstring of datumaro.plugins.coco_format.extractor.CocoLabelsExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.coco_format.extractor._CocoExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\extractor.py:docstring of datumaro.plugins.coco_format.extractor.CocoPanopticExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.coco_format.extractor._CocoExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\extractor.py:docstring of datumaro.plugins.coco_format.extractor.CocoStuffExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.coco_format.extractor._CocoExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\coco_format\format.py:docstring of datumaro.plugins.coco_format.format.CocoTask:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\icdar_format\extractor.py:docstring of datumaro.plugins.icdar_format.extractor.IcdarWordRecognitionExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.icdar_format.extractor._IcdarExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\icdar_format\extractor.py:docstring of datumaro.plugins.icdar_format.extractor.IcdarTextLocalizationExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.icdar_format.extractor._IcdarExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\icdar_format\extractor.py:docstring of datumaro.plugins.icdar_format.extractor.IcdarTextSegmentationExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.icdar_format.extractor._IcdarExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\icdar_format\format.py:docstring of datumaro.plugins.icdar_format.format.IcdarTask:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\kitti_format\converter.py:docstring of datumaro.plugins.kitti_format.converter.LabelmapType:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\kitti_format\extractor.py:docstring of datumaro.plugins.kitti_format.extractor.KittiSegmentationExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.kitti_format.extractor._KittiExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\kitti_format\extractor.py:docstring of datumaro.plugins.kitti_format.extractor.KittiDetectionExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.kitti_format.extractor._KittiExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\kitti_format\format.py:docstring of datumaro.plugins.kitti_format.format.KittiTask:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\kitti_raw_format\format.py:docstring of datumaro.plugins.kitti_raw_format.format.PoseStates:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\kitti_raw_format\format.py:docstring of datumaro.plugins.kitti_raw_format.format.OcclusionStates:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\kitti_raw_format\format.py:docstring of datumaro.plugins.kitti_raw_format.format.TruncationStates:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91m<unknown>:1: WARNING: py:class reference target not found: datumaro.plugins.openvino_plugin.launcher._OpenvinoImporter[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\camvid_format.py:docstring of datumaro.plugins.camvid_format.LabelmapType:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\cifar_format.py:docstring of datumaro.plugins.cifar_format.RestrictedUnpickler:1: WARNING: py:class reference target not found: _pickle.Unpickler[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\cityscapes_format.py:docstring of datumaro.plugins.cityscapes_format.LabelmapType:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\image_zip_format.py:docstring of datumaro.plugins.image_zip_format.Compression:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\mot_format.py:docstring of datumaro.plugins.mot_format.MotLabel:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\mots_format.py:docstring of datumaro.plugins.mots_format.MotsLabels:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.Algorithm:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.OverSamplingMethod:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.UnderSamplingMethod:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.NDR.__init__:: WARNING: py:class reference target not found: "random"[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.NDR.__init__:: WARNING: py:class reference target not found: "similarity"[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.NDR.__init__:: WARNING: py:class reference target not found: "uniform"[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.NDR.__init__:: WARNING: py:class reference target not found: "inverse"[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.NDR.__init__:: WARNING: py:class reference target not found: Algorithm Specific for[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\ndr.py:docstring of datumaro.plugins.ndr.NDR.__init__:: WARNING: py:class reference target not found: other subsets combined with the result[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter.SplitTask:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._TaskSpecificSplit._group_by_attr:: WARNING: py:class reference target not found: by_attributes[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._TaskSpecificSplit._split_unlabeled:: WARNING: py:class reference target not found: by_splits[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._ClassificationSplit.__init__:: WARNING: py:class reference target not found: optional[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._ReidentificationSplit.__init__:: WARNING: py:class reference target not found: optional[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\splitter.py:docstring of datumaro.plugins.splitter._InstanceSpecificSplit.__init__:: WARNING: py:class reference target not found: optional[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\transforms.py:docstring of datumaro.plugins.transforms.RemapLabels.DefaultAction:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.ClassificationValidator:1: WARNING: py:class reference target not found: datumaro.plugins.validators._TaskValidator[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.ClassificationValidator.compute_statistics:: WARNING: py:class reference target not found: IDataset object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.ClassificationValidator.compute_statistics:: WARNING: py:class reference target not found: A dict object containing statistics of the dataset.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.ClassificationValidator.generate_reports:: WARNING: py:class reference target not found: IDataset object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.ClassificationValidator.generate_reports:: WARNING: py:class reference target not found: Dict object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.ClassificationValidator.generate_reports:: WARNING: py:class reference target not found: List of validation reports[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.ClassificationValidator.generate_reports:: WARNING: py:class reference target not found: [39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.DetectionValidator:1: WARNING: py:class reference target not found: datumaro.plugins.validators._TaskValidator[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.DetectionValidator.compute_statistics:: WARNING: py:class reference target not found: IDataset object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.DetectionValidator.compute_statistics:: WARNING: py:class reference target not found: A dict object containing statistics of the dataset.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.DetectionValidator.generate_reports:: WARNING: py:class reference target not found: IDataset object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.DetectionValidator.generate_reports:: WARNING: py:class reference target not found: Dict object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.DetectionValidator.generate_reports:: WARNING: py:class reference target not found: List of validation reports[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.DetectionValidator.generate_reports:: WARNING: py:class reference target not found: [39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.SegmentationValidator:1: WARNING: py:class reference target not found: datumaro.plugins.validators._TaskValidator[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.SegmentationValidator.compute_statistics:: WARNING: py:class reference target not found: IDataset object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.SegmentationValidator.compute_statistics:: WARNING: py:class reference target not found: A dict object containing statistics of the dataset.[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.SegmentationValidator.generate_reports:: WARNING: py:class reference target not found: IDataset object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.SegmentationValidator.generate_reports:: WARNING: py:class reference target not found: Dict object[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.SegmentationValidator.generate_reports:: WARNING: py:class reference target not found: List of validation reports[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\validators.py:docstring of datumaro.plugins.validators.SegmentationValidator.generate_reports:: WARNING: py:class reference target not found: [39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\algorithm.py:docstring of datumaro.plugins.sampler.algorithm.algorithm.SamplingMethod:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\algorithm.py:docstring of datumaro.plugins.sampler.algorithm.algorithm.Algorithm:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\entropy.py:docstring of datumaro.plugins.sampler.algorithm.entropy.SampleEntropy.get_sample:: WARNING: py:class reference target not found: pandas.core.frame.DataFrame[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\entropy.py:docstring of datumaro.plugins.sampler.algorithm.entropy.SampleEntropy.get_sample:: WARNING: py:class reference target not found: Extracted sample data[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\entropy.py:docstring of datumaro.plugins.sampler.algorithm.entropy.SampleEntropy._get_sample_mixed:: WARNING: py:class reference target not found: pandas.core.frame.DataFrame[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\entropy.py:docstring of datumaro.plugins.sampler.algorithm.entropy.SampleEntropy._get_sample_mixed:: WARNING: py:class reference target not found: Extracted sample data[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\sampler\algorithm\entropy.py:docstring of datumaro.plugins.sampler.algorithm.entropy.SampleEntropy._rank_images:: WARNING: py:class reference target not found: pandas.core.frame.DataFrame[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\converter.py:docstring of datumaro.plugins.voc_format.converter.LabelmapType:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\extractor.py:docstring of datumaro.plugins.voc_format.extractor.VocClassificationExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.voc_format.extractor._VocExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\extractor.py:docstring of datumaro.plugins.voc_format.extractor.VocDetectionExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.voc_format.extractor._VocXmlExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\extractor.py:docstring of datumaro.plugins.voc_format.extractor.VocLayoutExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.voc_format.extractor._VocXmlExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\extractor.py:docstring of datumaro.plugins.voc_format.extractor.VocActionExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.voc_format.extractor._VocXmlExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\extractor.py:docstring of datumaro.plugins.voc_format.extractor.VocSegmentationExtractor:1: WARNING: py:class reference target not found: datumaro.plugins.voc_format.extractor._VocExtractor[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\format.py:docstring of datumaro.plugins.voc_format.format.VocTask:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\format.py:docstring of datumaro.plugins.voc_format.format.VocLabel:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\format.py:docstring of datumaro.plugins.voc_format.format.VocPose:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\format.py:docstring of datumaro.plugins.voc_format.format.VocBodyPart:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\plugins\voc_format\format.py:docstring of datumaro.plugins.voc_format.format.VocAction:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91m<unknown>:1: WARNING: py:class reference target not found: datumaro.components.annotation._Shape[39;49;00m
[91m<unknown>:1: WARNING: py:obj reference target not found: typing.Union[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\annotation_util.py:docstring of datumaro.util.annotation_util.max_bbox:: WARNING: py:class reference target not found: bbox[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\annotation_util.py:docstring of datumaro.util.annotation_util.mean_bbox:: WARNING: py:class reference target not found: bbox[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\annotation_util.py:docstring of datumaro.util.annotation_util.bbox_iou:: WARNING: py:class reference target not found: Union[Literal[-1], float][39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\annotation_util.py:docstring of datumaro.util.annotation_util.approximate_line:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\annotation_util.py:docstring of datumaro.util.annotation_util.approximate_line:: WARNING: py:class reference target not found: new_points[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\annotation_util.py:docstring of datumaro.util.annotation_util.approximate_line:: WARNING: py:class reference target not found: ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\annotation_util.py:docstring of datumaro.util.annotation_util.make_label_id_mapping:: WARNING: py:class reference target not found: map_id[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\annotation_util.py:docstring of datumaro.util.annotation_util.make_label_id_mapping:: WARNING: py:class reference target not found: callable[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\image.py:docstring of datumaro.util.image._IMAGE_BACKENDS:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\image.py:docstring of datumaro.util.image.decode_image:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\image.py:docstring of datumaro.util.image.lazy_image:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\image.py:docstring of datumaro.util.image.lazy_image.__init__:: WARNING: py:class reference target not found: numpy.ndarray[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\mask_tools.py:docstring of datumaro.util.mask_tools.crop_covered_segments:: WARNING: py:class reference target not found: A list of input segments' parts[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\mask_tools.py:docstring of datumaro.util.mask_tools.crop_covered_segments:: WARNING: py:class reference target not found: in the same order as input[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\scope.py:docstring of datumaro.util.scope.Scope.add:: WARNING: py:class reference target not found: datumaro.util.scope.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\scope.py:docstring of datumaro.util.scope.Scope.add:: WARNING: py:class reference target not found: datumaro.util.scope.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\scope.py:docstring of datumaro.util.scope.scope_add:: WARNING: py:class reference target not found: datumaro.util.scope.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\scope.py:docstring of datumaro.util.scope.scope_add:: WARNING: py:class reference target not found: datumaro.util.scope.T[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\test_utils.py:docstring of datumaro.util.test_utils.Dimensions:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
[91mC:\Git\update-api-docs-fix-docstrings\datumaro\datumaro\util\test_utils.py:docstring of datumaro.util.test_utils.Dimensions:1: WARNING: py:class reference target not found: enum.Enum[39;49;00m
